Repository Buly1601/MindYourTasks, pull requests merged in 2021-08, with the labels that each got.

#34 Changed redirect to render_template
  app/__init__.py
Labels: bug

#40 Redirectbug
  app/__init__.py
  user_conf.d/nginx-conf.conf
Labels: bug

#38 action bugs
  .github/workflows/deploy.yml
  app/__init__.py
Labels: bug

#49 Added Gif of the app
  README.md
Labels: documentation

#50 Readme update branch
  README.md
  app/static/images/chart.JPG
  app/static/images/gina.jpg
Labels: documentation

#51 Feature/dk/befeature our website done!!
  .gitignore
  app/__init__.py
  app/schema.sql
  app/static/styles/todo.css
  app/templates/todo.html
  app/todo_db.sql
  requirements.txt
  user_conf.d/nginx-conf.conf
Labels: enhancement

#52 added the secret
  app/__init__.py
Labels: bug
